# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitFaker < Formula
  desc ""
  homepage ""
  version "0.0.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/danieltaub96/git-faker/releases/v0.0.5/git-faker_0.0.5_darwin_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "2e365b1d963a4275c969375c1ca960718af0830cab4cea59220592f118a4a2e1"
    end
    if Hardware::CPU.arm?
      url "http://github.com/danieltaub96/git-faker/releases/v0.0.5/git-faker_0.0.5_darwin_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "86ec6171a8c3d34114b7c050a4c0a340e1068f9329a69bb3c99f48013a35a9de"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/danieltaub96/git-faker/releases/v0.0.5/git-faker_0.0.5_linux_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "ff5e9fb92950440e53aafc1a80dbc749d9154b44ec3156ad2e1861bae68627a8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/danieltaub96/git-faker/releases/v0.0.5/git-faker_0.0.5_linux_arm64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "e4c8d9928f488f6d9a5282dc1a3d5723cdf69aa97e50e25142fdc207375f94aa"
    end
  end

  depends_on "git"

  def install
    bin.install "git-faker"
  end
end
